# Generated by Django 2.0 on 2019-01-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_img', models.ImageField(upload_to='static/images/dishes')),
                ('dish_sum', models.CharField(max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='dishD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridient', models.CharField(max_length=1800)),
                ('instructions', models.CharField(max_length=18000)),
                ('about', models.CharField(max_length=1800)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foods.dish')),
            ],
        ),
    ]
