# Generated by Django 2.0 on 2019-01-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishd',
            name='about',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AlterField(
            model_name='dishd',
            name='ingridient',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AlterField(
            model_name='dishd',
            name='instructions',
            field=models.CharField(blank=True, max_length=18000, null=True),
        ),
    ]
