# Generated by Django 2.0 on 2019-01-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=136)),
                ('place_img', models.ImageField(upload_to='static/images/places')),
                ('place_sum', models.CharField(max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_it', models.CharField(max_length=3600)),
                ('why_so_famous', models.CharField(max_length=3600)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Place')),
            ],
        ),
    ]
