# Generated by Django 2.0 on 2019-01-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, max_length=36, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=36, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=36, null=True)),
                ('affairs', models.CharField(blank=True, max_length=36, null=True)),
                ('birthplace_place', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=36, null=True)),
                ('nationality', models.CharField(blank=True, max_length=36, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=36, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=36, null=True)),
                ('height', models.CharField(blank=True, max_length=36, null=True)),
                ('weight', models.CharField(blank=True, max_length=36, null=True)),
                ('education', models.CharField(blank=True, max_length=106, null=True)),
                ('horoscope', models.CharField(blank=True, max_length=36, null=True)),
                ('net_worth', models.CharField(blank=True, max_length=36, null=True)),
                ('about_career', models.CharField(blank=True, max_length=1600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=36)),
                ('act_img', models.ImageField(upload_to='static/images')),
                ('act_sum', models.CharField(max_length=1600)),
            ],
        ),
        migrations.AddField(
            model_name='actd',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actors.Actors'),
        ),
    ]
